package verify_test

import (
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/magnexis/taglock/config"
	"github.com/magnexis/taglock/contract"
	"github.com/magnexis/taglock/engine"
	"github.com/magnexis/taglock/namespace"
	"github.com/magnexis/taglock/verify"
)

func TestGenerateIsExplicitDeterministicAndProtectsUserFiles(t *testing.T) {
	directory := t.TempDir()
	filename := filepath.Join(directory, "model.go")
	const source = "package sample\n\ntype User struct { ID string `json:\"id\"` }\ntype Box[T any] struct { Value T `json:\"value\"` }\n"
	set := token.NewFileSet()
	file, err := parser.ParseFile(set, filename, source, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}
	info := &types.Info{Types: map[ast.Expr]types.TypeAndValue{}, Defs: map[*ast.Ident]types.Object{}, Uses: map[*ast.Ident]types.Object{}}
	pkg, err := (&types.Config{}).Check("example/sample", set, []*ast.File{file}, info)
	if err != nil {
		t.Fatal(err)
	}
	cfg := config.Default()
	cfg.Verification.Fixtures["example/sample.User"] = config.VerificationFixture{File: "testdata/user.json"}
	cfg.Verification.Fixtures["example/sample.Box"] = config.VerificationFixture{TypeArguments: []string{"string"}}
	contracts, issues := contract.BuildPackage([]*ast.File{file}, info, pkg, cfg, namespace.NewRegistry(nil))
	if len(issues) != 0 {
		t.Fatalf("contract issues: %v", issues)
	}
	files, err := verify.Generate(engine.Result{FileSet: set, Contracts: contracts}, cfg)
	if err != nil || len(files) != 1 {
		t.Fatalf("Generate: files=%d err=%v", len(files), err)
	}
	if !strings.Contains(string(files[0].Content), "Code generated by TagLock") || !strings.Contains(string(files[0].Content), "TestTagLockContract_User") || !strings.Contains(string(files[0].Content), "var value Box[string]") || !strings.Contains(string(files[0].Content), "reflect.DeepEqual") {
		t.Fatalf("unexpected generated test:\n%s", files[0].Content)
	}
	if _, err := os.Stat(files[0].Path); !os.IsNotExist(err) {
		t.Fatal("Generate wrote a file before explicit Write")
	}
	if err := os.WriteFile(files[0].Path, []byte("package sample\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := verify.Write(files); err == nil || !strings.Contains(err.Error(), "refusing to overwrite") {
		t.Fatalf("expected overwrite protection, got %v", err)
	}
}
