// Package verify generates optional runtime contract tests without executing them.
package verify

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/theworker02/taglock/config"
	"github.com/theworker02/taglock/engine"
)

const generatedName = "taglock_contract_verify_test.go"

type GeneratedFile struct {
	Path    string
	Content []byte
}
type typeEntry struct {
	name, typeExpression, fixture string
}

func Generate(result engine.Result, cfg config.Config) ([]GeneratedFile, error) {
	type packageData struct {
		name, dir string
		types     []typeEntry
	}
	packages := map[string]*packageData{}
	for _, item := range result.Contracts {
		position := result.FileSet.Position(item.Position)
		if !cfg.SelectContract(item.Package, position.Filename, item.Exported) || !item.Exported {
			continue
		}
		identity := item.Package + "." + item.TypeName
		configured, configuredOK := cfg.Verification.Fixtures[identity]
		if !configuredOK {
			configured, configuredOK = cfg.Verification.Fixtures[item.TypeName]
		}
		typeExpression := item.TypeName
		testName := item.TypeName
		if named, ok := item.DeclaredType.(*types.Named); ok && named.TypeParams() != nil && named.TypeParams().Len() > 0 {
			if !configuredOK || len(configured.TypeArguments) == 0 {
				continue
			}
			if len(configured.TypeArguments) != named.TypeParams().Len() {
				return nil, fmt.Errorf("verification fixture %s provides %d type arguments; %s requires %d", identity, len(configured.TypeArguments), item.TypeName, named.TypeParams().Len())
			}
			arguments := make([]types.Type, 0, len(configured.TypeArguments))
			for _, expression := range configured.TypeArguments {
				evaluated, err := types.Eval(result.FileSet, named.Obj().Pkg(), item.Position, expression)
				if err != nil {
					return nil, fmt.Errorf("verification fixture %s type argument %q is not a type in package scope: %w", identity, expression, err)
				}
				if !evaluated.IsType() {
					return nil, fmt.Errorf("verification fixture %s type argument %q is not a type in package scope", identity, expression)
				}
				arguments = append(arguments, evaluated.Type)
			}
			if _, err := types.Instantiate(nil, named, arguments, true); err != nil {
				return nil, fmt.Errorf("verification fixture %s cannot instantiate %s: %w", identity, item.TypeName, err)
			}
			typeExpression = item.TypeName + "[" + strings.Join(configured.TypeArguments, ", ") + "]"
			testName += "_Generic"
		} else if configuredOK && len(configured.TypeArguments) > 0 {
			return nil, fmt.Errorf("verification fixture %s provides type arguments for non-generic type %s", identity, item.TypeName)
		}
		entry := packages[item.Package]
		if entry == nil {
			entry = &packageData{name: item.File.Name.Name, dir: filepath.Dir(position.Filename)}
			packages[item.Package] = entry
		}
		fixture := ""
		if configuredOK {
			fixture = configured.File
		}
		entry.types = append(entry.types, typeEntry{name: testName, typeExpression: typeExpression, fixture: fixture})
	}
	paths := make([]string, 0, len(packages))
	for path := range packages {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	var resultFiles []GeneratedFile
	for _, packagePath := range paths {
		entry := packages[packagePath]
		sort.Slice(entry.types, func(i, j int) bool { return entry.types[i].name < entry.types[j].name })
		var source bytes.Buffer
		fmt.Fprintln(&source, "// Code generated by TagLock verify generate; DO NOT EDIT.")
		fmt.Fprintf(&source, "package %s\n\n", entry.name)
		hasFixtures := false
		for _, item := range entry.types {
			if item.fixture != "" {
				hasFixtures = true
			}
		}
		fmt.Fprintln(&source, "import (\n\t\"encoding/json\"")
		if hasFixtures {
			fmt.Fprintln(&source, "\t\"os\"")
			fmt.Fprintln(&source, "\t\"reflect\"")
		}
		fmt.Fprintln(&source, "\t\"testing\"\n)")
		for _, item := range entry.types {
			fmt.Fprintf(&source, "\nfunc TestTagLockContract_%s(t *testing.T) {\n\tvar value %s\n\tdata, err := json.Marshal(value)\n\tif err != nil { t.Fatalf(\"marshal zero %s: %%v\", err) }\n\tif !json.Valid(data) { t.Fatalf(\"%s produced invalid JSON\") }", item.name, item.typeExpression, item.typeExpression, item.typeExpression)
			if item.fixture != "" {
				fmt.Fprintf(&source, "\n\tfixture, err := os.ReadFile(%s)\n\tif err != nil { t.Fatalf(\"read configured fixture: %%v\", err) }\n\tif err := json.Unmarshal(fixture, &value); err != nil { t.Fatalf(\"unmarshal configured fixture: %%v\", err) }\n\tencoded, err := json.Marshal(value)\n\tif err != nil { t.Fatalf(\"marshal configured fixture: %%v\", err) }\n\tvar expected, actual any\n\tif err := json.Unmarshal(fixture, &expected); err != nil { t.Fatalf(\"normalize configured fixture: %%v\", err) }\n\tif err := json.Unmarshal(encoded, &actual); err != nil { t.Fatalf(\"normalize encoded fixture: %%v\", err) }\n\tif !reflect.DeepEqual(expected, actual) { t.Fatalf(\"fixture wire contract changed: expected %%s, got %%s\", fixture, encoded) }", strconv.Quote(filepath.ToSlash(item.fixture)))
			}
			fmt.Fprintln(&source, "\n}")
		}
		formatted, err := format.Source(source.Bytes())
		if err != nil {
			return nil, fmt.Errorf("format generated verifier for %s: %w", packagePath, err)
		}
		resultFiles = append(resultFiles, GeneratedFile{Path: filepath.Join(entry.dir, generatedName), Content: formatted})
	}
	return resultFiles, nil
}
func Write(files []GeneratedFile) error {
	for _, file := range files {
		if existing, err := os.ReadFile(file.Path); err == nil && !strings.HasPrefix(string(existing), "// Code generated by TagLock") {
			return fmt.Errorf("refusing to overwrite non-generated file %s", file.Path)
		} else if err != nil && !os.IsNotExist(err) {
			return err
		}
		if err := os.WriteFile(file.Path, file.Content, 0o644); err != nil {
			return err
		}
	}
	return nil
}
